// DOCX export (PW-056, spec 10 "v1 export: Clean DOCX"): written by the app from the stored document, with
// no external program. Citation labels, the bibliography and figure/table numbers come from the same pinned
// renderer the editor shows (editor-core references, STYLE_VERSION) — from the stored references and the
// owner's figure order only; nothing is generated by a model, and an id that resolves to nothing is shown as
// such ([?]), never filled in.
// Written: Word styles (Normal, Title, heading 1–6, Bibliography, Caption, a bordered table style), bold,
// italic, subscript, superscript, tables, citations as their labels, cross-references as "Figure N"/"Table N",
// a "References" section and a "Figure and table legends" section (captions from the latest figure version,
// else the title). Math is written as its LaTeX text (reported). The file is checked (./check.ts) and read
// back; an export with errors carries a "draft" header in the file itself.
import { bibliography, citationLabels, figureLabels, referenceOccurrences, STYLE_VERSION, type CitationStyle, type FigureMeta, type RefMeta } from '@pw/editor-core';
import { writeZip } from './zip.ts';

export const RENDERER_VERSION = 'pw-docx-export-1';
export type Mark = 'bold' | 'italic' | 'subscript' | 'superscript';
export interface OutInline { text: string; marks: Mark[] }
export type OutBlock =
  | { type: 'heading'; level: number; content: OutInline[] }
  | { type: 'paragraph'; style: 'Normal' | 'Bibliography' | 'Caption'; content: OutInline[] }
  | { type: 'table'; rows: OutInline[][][] };
export interface FigureIn extends FigureMeta { caption: string | null }

type Node = { type?: string; text?: string; marks?: { type: string }[]; attrs?: Record<string, unknown>; content?: Node[] };
const MARKS: Mark[] = ['bold', 'italic', 'subscript', 'superscript'];
// characters XML 1.0 cannot carry
// eslint-disable-next-line no-control-regex
export const XML_INVALID = /[\u0000-\u0008\u000B\u000C\u000E-\u001F￾￿]/g;
const esc = (s: string) => s.replace(XML_INVALID, '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// the document as blocks of styled text, with labels in place of citations and cross-references
export function layout(doc: unknown, refs: readonly RefMeta[], figures: readonly FigureIn[], style: CitationStyle) {
  const occ = referenceOccurrences(doc);
  const cit = citationLabels(occ.citations, refs, style);
  const fig = figureLabels(occ.figures, figures);
  let ci = 0;
  let fi = 0;
  const math: string[] = [];
  const typed: string[] = []; // plain text pieces, for the citation-like text check
  const inlines = (n: Node): OutInline[] => {
    const out: OutInline[] = [];
    for (const c of n.content ?? []) {
      if (c.type === 'text') {
        out.push({ text: c.text ?? '', marks: MARKS.filter((m) => (c.marks ?? []).some((x) => x.type === m)) });
        typed.push(c.text ?? '');
      } else if (c.type === 'citation') out.push({ text: cit.labels[ci++] ?? '[?]', marks: [] });
      else if (c.type === 'figure_ref') out.push({ text: fig.labels[fi++] ?? '[그림/표 없음]', marks: [] });
      else if (c.type === 'math_inline') {
        const latex = String(c.attrs?.latex ?? '');
        math.push(latex);
        out.push({ text: latex, marks: [] });
      }
    }
    return out;
  };
  const blocks: OutBlock[] = [];
  for (const b of ((doc as Node).content ?? [])) {
    if (b.type === 'heading') blocks.push({ type: 'heading', level: Math.min(6, Math.max(1, Number(b.attrs?.level ?? 1))), content: inlines(b) });
    else if (b.type === 'paragraph') blocks.push({ type: 'paragraph', style: 'Normal', content: inlines(b) });
    else if (b.type === 'table') blocks.push({ type: 'table', rows: (b.content ?? []).map((row) => (row.content ?? []).map((cell) => inlines(cell))) });
  }
  const bib = bibliography(occ.citations, refs, style);
  if (bib.length) {
    blocks.push({ type: 'heading', level: 1, content: [{ text: 'References', marks: [] }] });
    for (const e of bib) blocks.push({ type: 'paragraph', style: 'Bibliography', content: [{ text: `${e.label} ${e.text}`, marks: [] }] });
  }
  const legends = [...figures].filter((f) => fig.numbers.has(f.id)).sort((a, b) => (a.kind === b.kind ? (fig.numbers.get(a.id)! - fig.numbers.get(b.id)!) : a.kind === 'figure' ? -1 : 1));
  if (legends.length) {
    blocks.push({ type: 'heading', level: 1, content: [{ text: 'Figure and table legends', marks: [] }] });
    for (const f of legends) blocks.push({ type: 'paragraph', style: 'Caption', content: [{ text: `${f.kind === 'figure' ? 'Figure' : 'Table'} ${fig.numbers.get(f.id)}. ${(f.caption ?? f.title).trim()}`, marks: [] }] });
  }
  const cited = [...new Set(occ.citations.map((o) => o.referenceId))].map((id) => refs.find((r) => r.id === id)).filter((r): r is RefMeta => !!r);
  return {
    blocks, math, typed, cited,
    unresolvedCitations: occ.citations.filter((o) => !refs.some((r) => r.id === o.referenceId)).map((o) => o.referenceId),
    unresolvedFigures: occ.figures.filter((t) => !figures.some((f) => f.id === t)),
    styleVersion: STYLE_VERSION,
  };
}

const run = (i: OutInline) => {
  const pr = [i.marks.includes('bold') ? '<w:b/>' : '', i.marks.includes('italic') ? '<w:i/>' : '',
    i.marks.includes('subscript') ? '<w:vertAlign w:val="subscript"/>' : i.marks.includes('superscript') ? '<w:vertAlign w:val="superscript"/>' : ''].join('');
  return `<w:r>${pr ? `<w:rPr>${pr}</w:rPr>` : ''}<w:t xml:space="preserve">${esc(i.text)}</w:t></w:r>`;
};
const para = (style: string, content: OutInline[]) => `<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr>${content.filter((i) => i.text).map(run).join('')}</w:p>`;
function blockXml(b: OutBlock): string {
  if (b.type === 'heading') return para(`Heading${b.level}`, b.content);
  if (b.type === 'paragraph') return para(b.style, b.content);
  const cols = Math.max(1, ...b.rows.map((r) => r.length));
  const grid = `<w:tblGrid>${'<w:gridCol w:w="2000"/>'.repeat(cols)}</w:tblGrid>`;
  const rows = b.rows.map((r) => `<w:tr>${r.map((cell) => `<w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr>${para('Normal', cell)}</w:tc>`).join('')}</w:tr>`).join('');
  return `<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="0" w:type="auto"/></w:tblPr>${grid}${rows}</w:tbl><w:p/>`;
}

const W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"';
const HEADINGS = [1, 2, 3, 4, 5, 6].map((n) => `<w:style w:type="paragraph" w:styleId="Heading${n}"><w:name w:val="heading ${n}"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:qFormat/><w:pPr><w:keepNext/><w:spacing w:before="240" w:after="120"/><w:outlineLvl w:val="${n - 1}"/></w:pPr><w:rPr><w:b/><w:sz w:val="${[32, 28, 26, 24, 22, 22][n - 1]}"/></w:rPr></w:style>`).join('');
const STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles ${W}>
<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Malgun Gothic" w:cs="Times New Roman"/><w:sz w:val="24"/><w:lang w:val="en-US" w:eastAsia="ko-KR"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="160" w:line="360" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:qFormat/></w:style>
<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:qFormat/><w:rPr><w:b/><w:sz w:val="36"/></w:rPr></w:style>
${HEADINGS}
<w:style w:type="paragraph" w:styleId="Bibliography"><w:name w:val="Bibliography"/><w:basedOn w:val="Normal"/><w:pPr><w:ind w:left="720" w:hanging="720"/></w:pPr></w:style>
<w:style w:type="paragraph" w:styleId="Caption"><w:name w:val="Caption"/><w:basedOn w:val="Normal"/><w:rPr><w:i/><w:sz w:val="22"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Header"><w:name w:val="header"/><w:basedOn w:val="Normal"/></w:style>
<w:style w:type="table" w:styleId="TableGrid"><w:name w:val="Table Grid"/><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:left w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:right w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideH w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideV w:val="single" w:sz="4" w:space="0" w:color="auto"/></w:tblBorders></w:tblPr></w:style>
</w:styles>`;

// the file: body blocks, styles, and (for a draft) a header saying so
export function writeDocx(blocks: readonly OutBlock[], draftNote: string | null): Buffer {
  const header = draftNote ? `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:hdr ${W}>${para('Header', [{ text: draftNote, marks: ['bold'] }])}</w:hdr>` : null;
  const sect = `<w:sectPr>${header ? '<w:headerReference w:type="default" r:id="rIdHeader1"/>' : ''}<w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr>`;
  const document = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document ${W}><w:body>${blocks.map(blockXml).join('')}${sect}</w:body></w:document>`;
  const types = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>${header ? '<Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/>' : ''}</Types>`;
  const rels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>';
  const docRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>${header ? '<Relationship Id="rIdHeader1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/>' : ''}</Relationships>`;
  const entries: [string, string][] = [['[Content_Types].xml', types], ['_rels/.rels', rels], ['word/document.xml', document], ['word/styles.xml', STYLES], ['word/_rels/document.xml.rels', docRels]];
  if (header) entries.push(['word/header1.xml', header]);
  return writeZip(entries);
}
